module.exports = {
  UPCOMING_SCHEDULED_SUBMISSION_FOR_TODAY: 'UPCOMING_SCHEDULED_SUBMISSION_FOR_TODAY',
  CHANNEL_INACTIVE: 'CHANNEL_INACTIVE',
  NEXT_SUBMISSION_SCHEDULED_FOR_FUTURE_DATE: 'NEXT_SUBMISSION_SCHEDULED_FOR_FUTURE_DATE',
  SUBMISSION_WINDOW_OPEN_NO_SUBMISSIONS: 'SUBMISSION_WINDOW_OPEN_NO_SUBMISSIONS',
  SUBMISSION_WINDOW_OPEN_WITH_SUBMISSIONS: 'SUBMISSION_WINDOW_OPEN_WITH_SUBMISSIONS',
};
